name: nightly regression test run

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: actions-page
            file: tests/e2e/2-advanced-examples/actions.spec.ts
          - name: todo-page
            file: tests/e2e/1-getting-started/todo.test.spec.ts
          - name: api-requests
            file: tests/api/request.spec.ts

    name: Playwright â€“ ${{ matrix.test.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Show runner time (UTC)
        run: date -u

      - name: Show runner local time
        run: date

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run tests
        run: yarn playwright test ${{ matrix.test.file }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.test.name }}
          path: playwright-report/
          retention-days: 30
